### ISSUE TITLE
Network error - unable to connect to server 

### ISSUE THREAD

**Issue by stilsota** [Every-Flavor-Robotics/motorgo-mini-gui#1]
when using current PID tuning web app link on https://motorgo.net/getting-started

issue occurs when pasting generated link (from PID manager) from the serial terminal into online PID tuning web app

**Comment by SwapnilPande** [comment]
This is due to a mixed content error in communicating with the MotorGo on the local network. The website is served over HTTPS, but the MotorGo serves its data over HTTP. 

Having the Web GUI communicate with the MotorGo will require some proxy that handles communication, which is not worth developing for now. The current solution is to simply have users download the app as a desktop electron app.

For now, I will go ahead and take down the page hosting the Web GUI unitl we have a better alternative.
